### ISSUE TITLE
This repo is useless

### ISSUE THREAD

**Issue by aleixsanchis** [rodarima/app1#1]
Please consider deleting it

**Comment by rodarima** [comment]
Won't fix

El 16 de abril de 2020 20:24:52 CEST, Aleix Sanchis <notifications@github.com> escribió:
>Please consider deleting it
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rodarima/app1/issues/1

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
